[tool.poetry]
name = "xypattern"
version = "1.2.4"
description = "Library for handling x-y pattern data."
authors = ["Clemens Prescher <clemens.prescher@gmail.com>"]
license = "MIT"
readme = "README.md"
build = "build_xypattern.py"

classifiers = [
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'License :: OSI Approved :: MIT License',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Physics',
    'Topic :: Scientific/Engineering :: Chemistry',
    'Topic :: Scientific/Engineering :: Visualization',
    'Topic :: Scientific/Engineering :: Information Analysis',
]

include = [
    # C extensions must be included in the wheel distributions
    {path = "xypattern/util/*.so", format = "wheel"},
    {path = "xypattern/util/*.pyd", format = "wheel"},
]
exclude = ["tests/*"] # Exclude tests from package


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
pattern = "default-unprefixed"
style = "semver"

[tool.poetry-dynamic-versioning.substitution]
files = ["xypattern/__init__.py"]



[tool.poetry.dependencies]
python = ">=3.8, <3.16"
numpy = [
  { version = "^1.24.0", python = ">=3.8, <3.9" },
  { version = ">=1.26,<3.0", python = ">=3.9, <3.14" },
  { version = ">=2.3.3,<3.0", python = ">=3.14, <3.15" },
  { version = ">=2.5.2,<3.0", python = ">=3.15" }
]
scipy = [
  { version = "^1.9.3", python = "<3.10" },
  { version = "^1.11.3", python = ">=3.10, <3.14" },
  { version = "^1.16.1", python = ">=3.14, <3.15" },
  { version = "^1.18.1", python = ">=3.15" }
]


[tool.poetry.group.dev.dependencies]
cython = [
  { version = ">=3.1,<4", python = "<3.15" },
  { version = ">=3.3,<4", python = ">=3.15" }
]
pytest = ">=7.4.4,<10"
pytest-cov = ">=4.1,<8"
setuptools = ">=68.2.2"
sphinx = ">=6,<10"
sphinx-rtd-theme = ">=1.3,<4"
myst-parser = ">=0.18,<6"

[tool.poetry.scripts]
stitch_patterns = "xypattern.scripts.stitch_patterns:main"

[build-system]
requires = [
    "poetry-core>=1.9",
    "cython>=3.1,<4; python_version < '3.15'",
    "cython>=3.3,<4; python_version >= '3.15'",
    "setuptools>=68.2.2",
    "poetry-dynamic-versioning>=1.0,<2",
]
build-backend = "poetry_dynamic_versioning.backend"
